services:
  cim-be:
    image: 192.168.100.10:8443/cim-be/core:${VERSION_CORE}
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cim
networks:
  cim:
    name: cim
    driver: bridge
